apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-utbetaling
  namespace: tpts
  labels:
    team: tpts
spec:
  image: {{ image }}
  port: 8080
  azure:
    application:
      enabled: true
  replicas:
    min: 1
    max: 1
  ingresses:
    - {{ ingress.url }}
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: {{ kafka.pool }}
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: tiltakspenger-vedtak
          namespace: tpts
          cluster: {{ cluster }}
    outbound:
      rules:
        - application: tiltakspenger-iverksett
          namespace: teamdagpenger
      external:
